MemberJoinPrivate: 欢迎%name%加入本群
MemberJoinGroup: 欢迎%name%加入本群
MemberLeave: %name%离开了这个群！
ForbiddenWords: %name%已被%time%(S)禁言！
UmForbiddenWords: %name%禁言已被解除！
failUmForbiddenWords: %name%未被禁言
KickMeber: %name%禁言已被踢出！
Signsuccess: '签到成功,当前签到次数:%frequency%'
Signfail: 今天你已签到过了
Signinfo: 签到成功,当前签到次数：%frequency%